/////////////////////////////////////////////////////////////////////////////
// Name:        win10tweak_symbols.h
// Purpose:     Symbols file
// Author:      Richard W. Allen
// Modified by: 
// Created:     25/05/2017 01:41:11
// RCS-ID:      
// Copyright:   (C) 2017 Richard W. Allen
// Licence:     
/////////////////////////////////////////////////////////////////////////////

#define ID_WIN10TWEAK_SYMBOL_0 _("Win 10 Tweak")
#define ID_WIN10TWEAK_SYMBOL_1 _("Privacy Settings")
#define ID_WIN10TWEAK_SYMBOL_2 _("Allow Telemetry")
#define ID_WIN10TWEAK_SYMBOL_3 _("Wi-Fi Sense")
#define ID_WIN10TWEAK_SYMBOL_4 _("SmartScreen Filter")
#define ID_WIN10TWEAK_SYMBOL_5 _("Bing Search in Start Menu")
#define ID_WIN10TWEAK_SYMBOL_6 _("Location Tracking")
#define ID_WIN10TWEAK_SYMBOL_7 _("Feedback")
#define ID_WIN10TWEAK_SYMBOL_8 _("Advertising ID")
#define ID_WIN10TWEAK_SYMBOL_9 _("Cortana")
#define ID_WIN10TWEAK_SYMBOL_10 _("AutoLogger directory")
#define ID_WIN10TWEAK_SYMBOL_11 _("Diagnostics Tracking Service")
#define ID_WIN10TWEAK_SYMBOL_12 _("WAP Push Service")
#define ID_WIN10TWEAK_SYMBOL_13 _("Windows Update P2P")
#define ID_WIN10TWEAK_SYMBOL_14 _("&Local network")
#define ID_WIN10TWEAK_SYMBOL_15 _("&Internet")
#define ID_WIN10TWEAK_SYMBOL_16 _("Service Tweaks")
#define ID_WIN10TWEAK_SYMBOL_17 _("Sharing mapped drives between users")
#define ID_WIN10TWEAK_SYMBOL_18 _("Firewall")
#define ID_WIN10TWEAK_SYMBOL_19 _("Windows Defender")
#define ID_WIN10TWEAK_SYMBOL_20 _("Windows Update automatic restart")
#define ID_WIN10TWEAK_SYMBOL_21 _("Home Groups services")
#define ID_WIN10TWEAK_SYMBOL_22 _("Remote Assistance")
#define ID_WIN10TWEAK_SYMBOL_23 _("Remote Desktop w/o Network Level Authentication")
#define ID_WIN10TWEAK_SYMBOL_24 _("UAC level")
#define ID_WIN10TWEAK_SYMBOL_25 _("&Raise")
#define ID_WIN10TWEAK_SYMBOL_26 _("&Lower")
#define ID_WIN10TWEAK_SYMBOL_27 _("UI Tweaks")
#define ID_WIN10TWEAK_SYMBOL_28 _("Show Search button / box")
#define ID_WIN10TWEAK_SYMBOL_29 _("Show Task View button")
#define ID_WIN10TWEAK_SYMBOL_30 _("Show large icons in taskbar")
#define ID_WIN10TWEAK_SYMBOL_31 _("Show titles in taskbar")
#define ID_WIN10TWEAK_SYMBOL_32 _("Show all tray icons")
#define ID_WIN10TWEAK_SYMBOL_33 _("Show known file extensions")
#define ID_WIN10TWEAK_SYMBOL_34 _("Show hidden files")
#define ID_WIN10TWEAK_SYMBOL_35 _("Change default Explorer view to \"Computer\"")
#define ID_WIN10TWEAK_SYMBOL_36 _("Show Computer shortcut on desktop")
#define ID_WIN10TWEAK_SYMBOL_37 _("Add Desktop icon to computer namespace")
#define ID_WIN10TWEAK_SYMBOL_38 _("Add Documents icon to computer namespace")
#define ID_WIN10TWEAK_SYMBOL_39 _("Add Downloads icon to computer namespace")
#define ID_WIN10TWEAK_SYMBOL_40 _("Add Music icon to computer namespace")
#define ID_WIN10TWEAK_SYMBOL_41 _("Add Pictures icon to computer namespace")
#define ID_WIN10TWEAK_SYMBOL_42 _("Add Videos icon to computer namespace")
#define ID_WIN10TWEAK_SYMBOL_43 _("Action Center")
#define ID_WIN10TWEAK_SYMBOL_44 _("Lock Screen")
#define ID_WIN10TWEAK_SYMBOL_45 _("Autoplay")
#define ID_WIN10TWEAK_SYMBOL_46 _("Autorun")
#define ID_WIN10TWEAK_SYMBOL_47 _("Sticky keys prompt")
#define ID_WIN10TWEAK_SYMBOL_48 _("Remove applications")
#define ID_WIN10TWEAK_SYMBOL_49 _("OneDrive")
#define ID_WIN10TWEAK_SYMBOL_50 _("&Install and Enable")
#define ID_WIN10TWEAK_SYMBOL_51 _("&Uninstall")
#define ID_WIN10TWEAK_SYMBOL_52 _("Windows Media Player")
#define ID_WIN10TWEAK_SYMBOL_53 _("Work Folders Client")
#define ID_WIN10TWEAK_SYMBOL_54 _("Default Applications")
#define ID_WIN10TWEAK_SYMBOL_55 _("Default Apps")
#define ID_WIN10TWEAK_SYMBOL_56 _("3DBuilder")
#define ID_WIN10TWEAK_SYMBOL_57 _("&Install")
#define ID_WIN10TWEAK_SYMBOL_58 _("&Unistall")
#define ID_WIN10TWEAK_SYMBOL_59 _("&Don't touch")
#define ID_WIN10TWEAK_SYMBOL_60 _("Bing Finance")
#define ID_WIN10TWEAK_SYMBOL_61 _("Bing News")
#define ID_WIN10TWEAK_SYMBOL_62 _("Bing Sports")
#define ID_WIN10TWEAK_SYMBOL_63 _("Bing Weather")
#define ID_WIN10TWEAK_SYMBOL_64 _("Get Started")
#define ID_WIN10TWEAK_SYMBOL_65 _("Microsoft Office Hub")
#define ID_WIN10TWEAK_SYMBOL_66 _("Microsoft Solitaire Collection")
#define ID_WIN10TWEAK_SYMBOL_67 _("Microsoft People")
#define ID_WIN10TWEAK_SYMBOL_68 _("Microsoft Office One Note")
#define ID_WIN10TWEAK_SYMBOL_69 _("Microsoft Skype App")
#define ID_WIN10TWEAK_SYMBOL_70 _("Microsoft Windows Photos")
#define ID_WIN10TWEAK_SYMBOL_71 _("Microsoft Windows Alarms")
#define ID_WIN10TWEAK_SYMBOL_72 _("Microsoft Windows Camera")
#define ID_WIN10TWEAK_SYMBOL_73 _("More")
#define ID_WIN10TWEAK_SYMBOL_74 _("Microsoft Windows Communications Apps")
#define ID_WIN10TWEAK_SYMBOL_75 _("Microsoft Windows Maps")
#define ID_WIN10TWEAK_SYMBOL_76 _("Microsoft Windows Phone")
#define ID_WIN10TWEAK_SYMBOL_77 _("Microsoft Windows Sound Recorder")
#define ID_WIN10TWEAK_SYMBOL_78 _("Microsoft XBox App")
#define ID_WIN10TWEAK_SYMBOL_79 _("Microsoft Zune Music")
#define ID_WIN10TWEAK_SYMBOL_80 _("Microsoft Zune Video")
#define ID_WIN10TWEAK_SYMBOL_81 _("Microsoft App Connector")
#define ID_WIN10TWEAK_SYMBOL_82 _("Microsoft Connectivity Store")
#define ID_WIN10TWEAK_SYMBOL_83 _("Microsoft Office Sway")
#define ID_WIN10TWEAK_SYMBOL_84 _("Microsoft Messaging")
#define ID_WIN10TWEAK_SYMBOL_85 _("Microsoft Comms Phone")
#define ID_WIN10TWEAK_SYMBOL_86 _("Twitter")
#define ID_WIN10TWEAK_SYMBOL_87 _("Candy Crush Soda Saga")
#define ID_WIN10TWEAK_SYMBOL_88 _("&OK")
#define ID_WIN10TWEAK_SYMBOL_89 _("&Cancel")
